// +build !wasm

package main

import "net/http"

// ResourceProvider is the interface that describes a provider for resources.
//
// App resources are the mandatory resources required to run a PWA. They are
// generated by the Handler and are accessible from the root path. Eg:
//  "/app-worker.js"
//  "/manifest.webmanifest"
//  "/wasm_exec.js"
//
// Static resources are the resources used by the PWA such as the web assembly
// binary, styles, scripts, or images. They can be located on a localhost or a
// remote bucket. In order to avoid confusion with PWA required resources,
// static resources URL paths are always prefixed by "/web". Eg:
//  "/web/app.wasm"
//  "/web/main.css"
//  "/web/background.jpg"
//
// If the resource provider is an http.Handler, the handler is used to serve
// static resources requests.
type ResourceProvider interface {
	// The path to the root directory where app resources are accessible.
	AppResources() string

	// The path or URL where the web directory that contains static resources is
	// located.
	StaticResources() string

	// The URL of the app.wasm file. This must match the pattern:
	//  StaticResources/web/WASM_FILE.
	AppWASM() string

	// The URL of the robots.txt file. This must match the pattern:
	//  StaticResources/web/robots.txt.
	// DEPRECATED.
	RobotsTxt() string

	// The URL of the ads.txt file. This must match the pattern:
	//  StaticResources/web/ads.txt.
	// DEPRECATED.
	AdsTxt() string
}

// BroccoliDir returns a resource provider that serves static resources from a
// local directory located at the given path.
func BroccoliDir(path string) ResourceProvider {
	return broccoliDir{
		Handler: http.StripPrefix("/web/", br.Serve(path)),
		path:    path,
	}
}

type broccoliDir struct {
	http.Handler
	path string
}

func (d broccoliDir) AppResources() string {
	return ""
}

func (d broccoliDir) StaticResources() string {
	return ""
}

func (d broccoliDir) AppWASM() string {
	return "/web/app.wasm"
}

func (d broccoliDir) RobotsTxt() string {
	return "/web/robots.txt"
}

func (d broccoliDir) AdsTxt() string {
	return "/web/ads.txt"
}
